email: ""
sessionName: ""
normalMem: "9G"
bigMem: "36G"
bigCores: 4
steps: "basecalling demultiplexing filtering_Nanopore filtering_Illumina assembly annotation additional_mapping taxonomy_check download_pangenome annotate_pangenome analyse_pangenome"
tmp_dir: "tmp"
inputs:
  Nanopore: ""
  Illumina: ""
  Contigs: ""
  Alignment_short_reads: ""
  Gff: ""
  Genomes2Compare: "" # directory, genomes need to be gzipped and filenames end in fna.gz, all files are used
  Gffs2Compare: "" # directory, filenames need to end in gff, all files are used
  Additional_Illumina_samples: "" # tsv table with path, r1_file, r2_file, and se_file columns
genomeName: "isolate1"
outputdir: ""
db_path: ""
guppy:
  bin: "module load gcccuda/2019b\n/data/project/galore/TOOLS/ont-guppy-4.2.2./bin"
  model: "dna_r10.3_450bps_hac.cfg"
  flowcell: "FLO-MIN111"
  sequencing_kit: "SQK-LSK109"
  barcoding_kit: "EXP-NBD103 EXP-NBD114"
barcode: "01"
nanofilt:
  quality: 10
  length: 3000
trimmomatic:
  adapter: "TruSeq3-PE"
  leading: 20
  minlen: 40
  palindrome_clip_threshold: 30
  simple_clip_threshold: 10
  trailing: 20
  seed_mismatch: 2
  window_size: 1
  window_quality: 3
  strictness: 0.5
  target_length: 40
nextseq: false
illumina_filter: "phiX174"
unicycler:
  keep: 2
  mode: normal
  linear_seqs: 0
  min_fasta_length: 100
hmm_DBs: "KEGG essential Pfam_A Resfams Cas dbCAN metacyc SwissProt TIGRPFAM"
hmm_settings:
  KEGG:
    cutoff: ""
    trim: "--trimall"
  essential:
    cutoff: "--cut_tc"
    trim: ""
  metacyc:
    cutoff: ""
    trim: "--trimall"
  Cas:
    cutoff: ""
    trim: ""
  Pfam_A:
    cutoff: "--cut_tc"
    trim: ""
  SwissProt:
    cutoff: ""
    trim: "--trimall"
  TIGRPFAM:
    cutoff: ""
    trim: ""
  dbCAN:
    cutoff: ""
    trim: ""
  Resfams:
    cutoff: ""
    trim: ""
pangenome_download:
  species: "" #needs to be a taxstring, separated by semicolon and using d__ etc, space between genus and species name in species part
  use_gtdb_relatives: false #gtdb relatives are usually less than 95% similar to the genome of interest, so false is usually the best option
  max_genomes: 50
  path_to_metadata: ""
  path_to_taxonomy: ""
