__default__:
  call: "sbatch"
  mem_per_cpu: "--mem-per-cpu "
  partition: ""
  runtime: "-t"
  threads: "-n"
  stdout: "galorious.{rule}.{wildcards}.stdout"

guppy_basecalling:
  partition: '-G 1'

guppy_demulti:
  partition: '-G 1'

