$schema: "http://json-schema.org/draft-07/schema#"

description: galorious Snakemake configuration file

type: object

properties:
  steps:
    type: string
  email:
    type: string
  sessionName:
    type: string
  normalMem:
    type: string
  tmp_dir:
    type: string
  genomeName:
    type: string
  outputdir:
    type: string
  db_path:
    type: string
  hmm_DBs:
    type: string
  inputs:
    type: object
    properties:
      Nanopore:
        type: string
      Illumina:
        type: string
      Contigs:
        type: string
      Alignment_short_reads:
        type: string
      Gff:
        type: string
      Genomes2Compare:
        type: string
  guppy:
    type: object
    properties:
      bin:
        type: string
      model:
        type: string
      flowcell:
        type: string
      sequencing_kit:
        type: string
      barcoding_kit:
        type: string
  trimmomatic:
    type: object
    properties:
      adapter:
        type: string
      leading:
        type: number
        minimum: 0
      minlen:
        type: number
        minimum: 0
      palindrome_clip_threshold:
        type: number
        minimum: 0
      simple_clip_threshold:
        type: number
        minimum: 0
      trailing:
        type: number
        minimum: 0
      seed_mismatch:
        type: number
        minimum: 0
      window_size:
        type: number
        minimum: 1
      window_quality:
        type: number
        minimum: 0
      strictness:
        type: number
      target_length:
        type: number
        minimum: 0
  hmm_settings:
    type: object
